import datetime

import streamlit as st
import datetime

st.header("STUDENT REGISTRATION FORM")
my_form = st.form(key = "form-1")
fname =  my_form.text_input("Enter the First Name:")
lname =  my_form.text_input("Enter the Last Name:")
email = my_form.text_input("Enter Your Email id:")
mobile = my_form.text_input("Enter Mobile Number:")
gender = my_form.radio('Gender',('Male','Female'))
dob = my_form.date_input("Enter your Date of Birth:",min_value=datetime.date(1990,1,1))
addr = my_form.text_area("Enter Your Address")
city = my_form.text_input("Enter Your City Name:")
pin = my_form.number_input("Enter Your Area PIN")
state = my_form.text_input("Enter The State Name")
Qualification=['degree','masters']
Qualification=my_form.selectbox('Qualification',Qualification)
specialization1=my_form.checkbox("Computer science")
specialization2=my_form.checkbox('Information technology')
specialization1=my_form.checkbox("Tele Communication")
password = my_form.text_input("Enter your password")
my_form._form_submit_button("Registered")
st.write("First name: ",fname)
st.write("Last name: ",lname)
st.write("Email: ",email)
st.write("Mobile number:",mobile)
st.write("Gender:",gender)
st.write("DOB: ",dob)
st.write("Address: ",addr)
st.write("City:",city)
st.write("PIN",pin)
st.write("State",state)
st.write('Qulification:', Qualification)
st.write("Password",password)