print("hello")
print('hello')
print("python", "java", "web")
print("welcome to")
print("bengaluru")
print("welcome to", end=' ')
print("bengaluru")
print("wel to ", end='/')
print("bel")
print("web", "java", "pyt", sep='/')
print("pyt", "java", end=' ', sep=' and ')
print("are the programming language")

